pipeline {
  agent any
  tools { maven 'Maven3' }
  stages {
    stage('Checkout') { steps { checkout scm } }
    stage('Build') { steps { bat 'mvn -B clean package' } }
    stage('Test')  { steps { bat 'mvn test' }
      post { always { junit '**/target/surefire-reports/*.xml' } } }
    stage('Archive') {
      steps { archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true }
    }
  }
}
